# Generated by Django 5.2 on 2026-09-11 23:34

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_poblar_mesas'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonConfig',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.PositiveSmallIntegerField(default=8)),
            ],
        ),
    ]
