from django.urls import path

from .admin_views import (
    admin_view,
    admin_platos,
    admin_plato_crear,
    admin_plato_editar,
    admin_plato_retirar,
    admin_plato_reactivar,
    admin_alergenos,
    admin_alergeno_eliminar,
    admin_mesas,
    admin_mesas_retiradas,
    admin_mesa_crear,
    admin_mesas_redimensionar,
    admin_mesa_retirar,
    admin_mesa_reactivar,
    admin_mesa_borrar,
    admin_mesa_mover,
    admin_meseros,
    admin_mesero_crear,
    admin_admins,
    admin_admin_crear,
    admin_reservas,
    admin_reserva_cancelar,
    admin_clientes,
    admin_clientes_desactivados,
    admin_cliente_editar,
    admin_cliente_desactivar,
    admin_cliente_activar,
)
from .views import (
    perfil_view,
    mesero_view,
    mesas_estado,
    tomar_mesa,
    sentar_invitado,
    cancelar_invitado,
    orden_agregar,
    orden_quitar,
    orden_cerrar,
)

urlpatterns = [
    path('perfil/', perfil_view, name='perfil'),
    path('mesero/', mesero_view, name='mesero'),
    path('mesero/mesas/', mesas_estado, name='mesas_estado'),
    path('mesero/tomar/', tomar_mesa, name='tomar_mesa'),
    path('mesero/invitado/', sentar_invitado, name='sentar_invitado'),
    path('mesero/invitado/cancelar/', cancelar_invitado, name='cancelar_invitado'),
    path('mesero/orden/agregar/', orden_agregar, name='orden_agregar'),
    path('mesero/orden/quitar/', orden_quitar, name='orden_quitar'),
    path('mesero/orden/cerrar/', orden_cerrar, name='orden_cerrar'),
    path('admin/', admin_view, name='admin'),
    path('admin/platos/', admin_platos, name='admin_platos'),
    path('admin/platos/crear/', admin_plato_crear, name='admin_plato_crear'),
    path('admin/platos/<str:pk>/editar/', admin_plato_editar, name='admin_plato_editar'),
    path('admin/platos/<str:pk>/retirar/', admin_plato_retirar, name='admin_plato_retirar'),
    path('admin/platos/<str:pk>/reactivar/', admin_plato_reactivar, name='admin_plato_reactivar'),
    path('admin/alergenos/', admin_alergenos, name='admin_alergenos'),
    path('admin/alergenos/<str:pk>/eliminar/', admin_alergeno_eliminar, name='admin_alergeno_eliminar'),
    path('admin/mesas/', admin_mesas, name='admin_mesas'),
    path('admin/mesas/retiradas/', admin_mesas_retiradas, name='admin_mesas_retiradas'),
    path('admin/mesas/crear/', admin_mesa_crear, name='admin_mesa_crear'),
    path('admin/mesas/redimensionar/', admin_mesas_redimensionar, name='admin_mesas_redimensionar'),
    path('admin/mesas/<str:pk>/retirar/', admin_mesa_retirar, name='admin_mesa_retirar'),
    path('admin/mesas/<str:pk>/reactivar/', admin_mesa_reactivar, name='admin_mesa_reactivar'),
    path('admin/mesas/<str:pk>/borrar/', admin_mesa_borrar, name='admin_mesa_borrar'),
    path('admin/mesas/<str:pk>/mover/', admin_mesa_mover, name='admin_mesa_mover'),
    path('admin/meseros/', admin_meseros, name='admin_meseros'),
    path('admin/meseros/crear/', admin_mesero_crear, name='admin_mesero_crear'),
    path('admin/admins/', admin_admins, name='admin_admins'),
    path('admin/admins/crear/', admin_admin_crear, name='admin_admin_crear'),
    path('admin/reservas/', admin_reservas, name='admin_reservas'),
    path('admin/reservas/<str:pk>/cancelar/', admin_reserva_cancelar, name='admin_reserva_cancelar'),
    path('admin/clientes/', admin_clientes, name='admin_clientes'),
    path('admin/clientes/desactivados/', admin_clientes_desactivados, name='admin_clientes_desactivados'),
    path('admin/clientes/<str:pk>/editar/', admin_cliente_editar, name='admin_cliente_editar'),
    path('admin/clientes/<str:pk>/desactivar/', admin_cliente_desactivar, name='admin_cliente_desactivar'),
    path('admin/clientes/<str:pk>/activar/', admin_cliente_activar, name='admin_cliente_activar'),
]
